# fly.toml app configuration file generated for n8n-financial-info on 2025-11-08T11:38:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-financial-info'
primary_region = 'gru'

[build]
  image = 'n8nio/n8n:latest'

[env]
  EXECUTIONS_MODE = 'regular'
  EXECUTIONS_PROCESS = 'main'
  GENERIC_TIMEZONE = 'America/Sao_Paulo'
  N8N_EDITOR_BASE_URL = 'https://n8n-financial-info.fly.dev'
  N8N_METRICS = 'false'
  N8N_PORT = '5678'
  NODE_ENV = 'production'
  TZ = 'America/Sao_Paulo'

[[mounts]]
  source = 'n8n_data'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 5678

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '2s'
    grace_period = '10s'
    method = 'get'
    path = '/healthz'
    protocol = 'http'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
